analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
config-version: 2
macro-paths:
- macros
model-paths:
- models
models:
  dbt_test26:
    marts:
      +materialized: table
    staging:
      +materialized: view
name: dbt_test26
profile: dbt_test26
seed-paths:
- seeds
snapshot-paths:
- snapshots
target-path: target
test-paths:
- tests
version: 1.0.0
